dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    python: "3.8-dev"
    python: "nightly"

# command to install dependencies
# install:
#  - pip install your_package
#    pip install git+https://github.com/blampe/IbPy.git

# command to run tests
script: cd tests && nosetests -v -v
